const enum damageType {
	unknown,
	slashing,
	piercing,
	blunt,
	shot,
	magic,
	breath,
	sound,
	limitBreak,
}

const enum damageAspect {
	unknown,
	fire,
	ice,
	wind,
	earth,
	lightning,
	water,
	unaspected,
}

const enum elementType {
	umbral, // Water, Earth, Ice
	astral, // Fire, Wind, Lightning
	physical,
}

export const BLU_STATUSES = {
	PETRIFICATION: {
		id: 1,
		name: 'Petrification',
		icon: 'https://xivapi.com/i/015000/015001.png',
	},
	STUN: {
		id: 2,
		name: 'Stun',
		icon: 'https://xivapi.com/i/015000/015004.png',
	},
	SLOW: {
		id: 9,
		name: 'Slow',
		icon: 'https://xivapi.com/i/015000/015009.png',
	},
	BIND: {
		id: 13,
		name: 'Bind',
		icon: 'https://xivapi.com/i/015000/015003.png',
	},
	AQUA_BREATH: {
		id: 1736,
		name: 'Dropsy',
		icon: 'https://xivapi.com/i/013000/013514.png',
		damageType: damageType.magic,
		damageAspect: damageAspect.water,
		elementType: elementType.umbral,
		dotPotency: 20,
		duration: 12,
		maxTicks: 4,
	},
	BLEEDING: {
		id: 1714,
		name: 'Bleeding',
		icon: 'https://xivapi.com/i/013000/013501.png',
		damageType: damageType.magic,
		damageAspect: damageAspect.unaspected,
		dotPotency: {
			'Aetherial Spark': 50,
			'Song of Torment': 50,
			'Nightbloom': 75,
		},
		duration: {
			'Aetherial Spark': 15,
			'Song of Torment': 30,
			'Nightbloom': 60,
		},
		maxTicks: {
			'Aetherial Spark': 5,
			'Song of Torment': 10,
			'Nightbloom': 20,
		},
		notes: "Applied by 11386 Song of Torment, 23281 Aetherial Spark, and 23290 Nightbloom, with different durations and potencies. Will overwrite each other."
	},
	BRISTLE: {
		id: 1716,
		name: 'Boost',
		icon: 'https://xivapi.com/i/013000/013503.png',
		damageDoneMultipler: 1.5,
		duration: 30,
		notes: "Only applies to Spells, not Abilities."
	},
	ICE_SPIKES: {
		id: 1720,
		name: 'Ice Spikes',
		icon: 'https://xivapi.com/i/013000/013507.png',
		damageType: damageType.magic,
		damageAspect: damageAspect.ice,
		elementType: elementType.umbral,
		counterPotency: 40,
		duration: 15,
	},
	OFF_GUARD: {
		id: 1717,
		name: 'Off-guard',
		icon: 'https://xivapi.com/i/013000/013504.png',
		damageReceivedMultiplier: 1.05,
		duration: 15,
	},
	MALODOROUS: {
		id: 1715,
		name: 'Malodorous',
		icon: 'https://xivapi.com/i/013000/013502.png',
		damageDoneMultiplier: 0.9,
		duration: 15,
	},
	BAD_BREATH_POISON: {
		id: 18,
		name: 'Poison',
		icon: 'https://xivapi.com/i/015000/015007.png',
		damageType: damageType.magic,
		damageAspect: damageAspect.unaspected,
		dotPotency: 20,
		duration: 15,
		maxTicks: 5,
	},
	DIAMONDBACK: {
		id: 1722,
		name: 'Diamondback',
		icon: 'https://xivapi.com/i/013000/013509.png',
		damageReceivedMultipler: 0.1,
		duration: 10,
	},
	MIGHTY_GUARD: {
		id: 1719,
		name: 'Mighty Guard',
		icon: 'https://xivapi.com/i/013000/013506.png',
		damageReceivedMultipler: 0.6,
		damageDoneMultipler: 0.6,
	},
	TOAD_OIL: {
		id: 1737,
		name: 'Toad Oil',
		icon: 'https://xivapi.com/i/013000/013515.png',
		evasionMultipler: 1.2,
		duration: 180,
	},
	DEEP_FREEZE: {
		id: 1731,
		name: 'Deep Freeze',
		icon: 'https://xivapi.com/i/013000/013513.png',
	},
	WAXING_NOCTURNE: {
		id: 1718,
		name: 'Waxing Nocturne',
		icon: 'https://xivapi.com/i/013000/013505.png',
		damageDoneMultiplier: 1.5,
		duration: 15,
	},
	WANING_NOCTURNE: {
		id: 1727,
		name: 'Waning Nocturne',
		icon: 'https://xivapi.com/i/013000/013512.png',
		duration: 15,
	},
	DOOM: {
		id: 1738,
		name: 'Doom',
		icon: 'https://xivapi.com/i/013000/013516.png',
		duration: 15,
		notes: "Target is instantly killed when effect expires."
	},
	PECULIAR_LIGHT: {
		id: 1721,
		name: 'Peculiar Light',
		icon: 'https://xivapi.com/i/013000/013508.png',
		damageReceivedMultipler: 1.05,
		limitToDamageType: damageType.magic,
		duration: 15,
	},
	FEATHER_RAIN: {
		id: 1723,
		name: 'Windburn',
		icon: 'https://xivapi.com/i/013000/013510.png',
		damageType: damageType.magic,
		damageAspect: damageAspect.wind,
		elementType: elementType.astral,
		dotPotency: 40,
		duration: 6,
		maxTicks: 2,
	},
	VEIL_OF_THE_WHORL: {
		id: 1724,
		name: 'Veil of the Whorl',
		icon: 'https://xivapi.com/i/013000/013511.png',
		damageType: damageType.magic,
		damageAspect: damageAspect.water,
		elementType: elementType.umbral,
		counterPotency: 50,
		duration: 30,
	},
	GOBSKIN: {
		id: 2114,
		name: 'Gobskin',
		icon: 'https://xivapi.com/i/013000/013517.png',
		shieldPotency: {
			'none': 100,
			'Aetheric Mimicry: Healer': 250,
		},
		duration: 30,
	},
	MAGIC_HAMMER: {
		id: 2115,
		name: 'Conked',
		icon: 'https://xivapi.com/i/013000/013518.png',
		damageDoneMultipler: 0.9,
		limitToDamageType: damageType.magic,
		duration: 10,
	},
	AVAIL_MEATILY_SHIELDED: {
		id: 2116,
		name: 'Meatily Shielded',
		icon: 'https://xivapi.com/i/013000/013519.png',
		duration: 12,
	},
	AVAIL_MEAT_SHIELD: {
		id: 2117,
		name: 'Meat Shield',
		icon: 'https://xivapi.com/i/013000/013520.png',
		duration: 12,
	},
	WHISTLE: {
		id: 2118,
		name: 'Harmonized',
		icon: 'https://xivapi.com/i/013000/013521.png',
		damageDoneMultipler: 1.8,
		limitToElementType: elementType.physical,
		duration: 30,
		notes: "Only applies to Spells, not Abilities."
	},
	CACTGUARD: {
		id: 2119,
		name: 'Cactguard',
		icon: 'https://xivapi.com/i/013000/013522.png',
		damageReceivedMultipler: {
			'none': 0.95,
			'Aetheric Mimicry: Tank': 0.85,
		},
		duration: 6,
	},
	DEVOUR: {
		id: 2120,
		name: 'HP Boost',
		icon: 'https://xivapi.com/i/013000/013523.png',
		maxHpMultiplier: 1.2,
		duration: {
			'none': 15,
			'Aetheric Mimicry: Tank': 70,
		},
	},
	CONDENSED_LIBRA_ASTRAL: {
		id: 2121,
		name: 'Astral Attenuation',
		icon: 'https://xivapi.com/i/013000/013524.png',
		damageReceivedMultiplier: 1.05,
		limitToElementType: elementType.astral,
		duration: 30,
	},
	CONDENSED_LIBRA_UMBRAL: {
		id: 2122,
		name: 'Umbral Attenuation',
		icon: 'https://xivapi.com/i/013000/013525.png',
		damageReceivedMultiplier: 1.05,
		limitToElementType: elementType.umbral,
		duration: 30,
	},
	CONDENSED_LIBRA_PHYSICAL: {
		id: 2123,
		name: 'Physical Attenuation',
		icon: 'https://xivapi.com/i/013000/013526.png',
		damageReceivedMultiplier: 1.05,
		limitToElementType: elementType.physical,
		duration: 30,
	},
	MIMICRY_TANK: {
		id: 2124,
		name: 'Aetherial Mimicry: Tank',
		icon: 'https://xivapi.com/i/013000/013527.png',
	},
	MIMICRY_DPS: {
		id: 2125,
		name: 'Aetherial Mimicry: DPS',
		icon: 'https://xivapi.com/i/013000/013528.png',
		critRateAdditive: 0.2,
		directHitRateAdditive: 0.2,
	},
	MIMICRY_HEALER: {
		id: 2126,
		name: 'Aetherial Mimicry: Healer',
		icon: 'https://xivapi.com/i/013000/013529.png',
		healingPotencyMultiplier: 1.2,
	},
	SURPANAKHA: {
		id: 2130,
		name: 'Surpanakha\'s Fury',
		icon: 'https://xivapi.com/i/019000/019581.png',
		damageDoneMultiplierPerStack: {
			'Surpanakha': 0.5,
		},
		duration: 3,
		stacksApplied: 1,
		maxStacks: 3,
	},
	PHANTOM_FLURRY: {
		id: 2502,
		name: 'Phantom Flurry',
		icon: 'https://xivapi.com/i/013000/013541.png',
		damageType: damageType.blunt,
		elementType: elementType.physical,
		dotPotency: 200,
		duration: 5,
		maxTicks: 6,
		notes: "Ground effect, ticks once per second, similar to MCH Flamethrower."
	},
	COLD_FOG: {
		id: 2493,
		name: 'Cold Fog',
		icon: 'https://xivapi.com/i/013000/013532.png',
		duration: 5,
	},
	TOUCH_OF_FROST: {
		id: 2494,
		name: 'Touch of Frost',
		icon: 'https://xivapi.com/i/013000/013533.png',
		duration: 15,
	},
	TINGLING: {
		id: 2492,
		name: 'Tingling',
		icon: 'https://xivapi.com/i/013000/013531.png',
		damagePotencyAdditive: 100,
		limitToElementType: elementType.physical,
		duration: 15,
	},
	ANGELS_SNACK: {
		id: 2495,
		name: 'Angel\'s Snack',
		icon: 'https://xivapi.com/i/013000/013534.png',
		hotPotency: 200,
		duration: 15,
		maxTicks: 5,
	},
	CHELONIAN_GATE: {
		id: 2496,
		name: 'Chelonian Gate',
		icon: 'https://xivapi.com/i/013000/013535.png',
		damageReceivedMultiplier: 0.8,
		duration: 10,
	},
	AUSPICIOUS_TRANCE: {
		id: 2497,
		name: 'Auspicious Trance',
		icon: 'https://xivapi.com/i/013000/013536.png',
	},
	BASIC_INSTINCT: {
		id: 2498,
		name: 'Basic Instinct',
		icon: 'https://xivapi.com/i/013000/013537.png',
		damageDoneMultiplier: 2,
		healingPotencyMultiplier: 2,
		notes: "Ignores the damage done penalty from Mighty Guard."
	},
	INCENDIARY_BURNS: {
		id: 2499,
		name: 'Incendiary Burns',
		icon: 'https://xivapi.com/i/013000/013538.png',
		damageType: damageType.magic,
		damageAspect: damageAspect.fire,
		elementType: elementType.astral,
		dotPotency: 50,
		duration: 15,
		maxTicks: 5,
	},
	DRAGON_FORCE: {
		id: 2500,
		name: 'Dragon Force',
		icon: 'https://xivapi.com/i/013000/013539.png',
		damageReceivedMultipler: {
			'none': 0.8,
			'Aetheric Mimicry: Tank': 0.6,
		},
		duration: 15,
	},
	LIGHTHEADED: {
		id: 2501,
		name: 'Lightheaded',
		icon: 'https://xivapi.com/i/013000/013540.png',
		duration: 5,
	},
	SCHILTRON: {
		id: 3631,
		name: 'Schiltron',
		icon: 'https://xivapi.com/i/013000/013542.png',
		damageType: damageType.magic,
		damageAspect: damageAspect.unaspected,
		counterPotency: {
			'none': 50,
			'Aetheric Mimicry: Tank': 100,
		},
		duration: 15,
	},
	BREATH_OF_MAGIC: {
		id: 3712,
		name: 'Breath of Magic',
		icon: 'https://xivapi.com/i/013000/013553.png',
		damageType: damageType.magic,
		damageAspect: damageAspect.unaspected,
		dotPotency: 120,
		duration: 60,
		maxTicks: 20,
		notes: "Only one copy of this status may be present per target."
	},
	BEGRIMED: {
		id: 3636,
		name: 'Begrimed',
		icon: 'https://xivapi.com/i/013000/013546.png',
		damageType: damageType.magic,
		damageAspect: damageAspect.earth,
		elementType: elementType.umbral,
		dotPotency: 10,
		duration: 9,
		maxTicks: 3,
	},
	SPICK_AND_SPAN: {
		id: 3637,
		name: 'Spick-and-span',
		icon: 'https://xivapi.com/i/019000/019447.png',
		hotPotencyPerStack: 50,
		duration: 15,
		stacksApplied: 1,
		maxStacks: 6,
	},
	BLU_PHYSICAL_VULN_DOWN: {
		id: 3638,
		name: 'Physical Vulnerability Down',
		icon: 'https://xivapi.com/i/013000/013547.png',
		damageReceviedMultiplier: 0.5,
		limitToElementType: elementType.physical,
		duration: 10,
	},
	BLU_MAGIC_VULN_DOWN: {
		id: 3639,
		name: 'Magic Vulnerability Down',
		icon: 'https://xivapi.com/i/013000/013548.png',
		damageReceviedMultiplier: 0.5,
		limitToDamageType: damageType.magic,
		duration: 10,
	},
	WINGED_REPROBATION: {
		id: 3640,
		name: 'Winged Reprobation',
		icon: 'https://xivapi.com/i/019000/019454.png',
		stacksApplied: 1,
		maxStacks: 4,
	},
	WINGED_REDEMPTION: {
		id: 3641,
		name: 'Winged Redemption',
		icon: 'https://xivapi.com/i/013000/013549.png',
		duration: 10,
	},
	CANDY_CANE: {
		id: 3642,
		name: 'Candy Cane',
		icon: 'https://xivapi.com/i/013000/013550.png',
		damageDoneMultiplier: 0.9,
		limitToElementType: elementType.physical,
		duration: 10,
	},
	MORTAL_FLAME: {
		id: 3643,
		name: 'Mortal Flame',
		icon: 'https://xivapi.com/i/013000/013551.png',
		damageType: damageType.magic,
		damageAspect: damageAspect.fire,
		elementType: elementType.astral,
		dotPotency: 40,
		notes: "Only one copy of this status may be present per target. Duration lasts until target dies or combat ends. Status re-applies itself every tick, but snapshots buffs on initial application."
	},
	APOKALYPSIS: {
		id: 3644,
		name: 'Apokalypsis',
		icon: 'https://xivapi.com/i/013000/013552.png',
		damageType: damageType.magic,
		damageAspect: damageAspect.unaspected,
		dotPotency: 140,
		duration: 10,
		maxTicks: 11,
		notes: "Ground effect, ticks once per second, similar to MCH Flamethrower."
	},
}

export const BLU_ACTIONS = {
	WATER_CANNON: {
		id: 11385,
		name: 'Water Cannon',
		icon: 'https://xivapi.com/i/003000/003253.png',
		damageType: damageType.magic,
		damageAspect: damageAspect.water,
		elementType: elementType.umbral,
		attackPotency: 200,
	},
	FLAME_THROWER: {
		id: 11402,
		name: 'Flame Thrower',
		icon: 'https://xivapi.com/i/003000/003270.png',
		damageType: damageType.magic,
		damageAspect: damageAspect.fire,
		elementType: elementType.astral,
		attackPotency: 220,
		aoeAttackPotency: 110,
	},
	AQUA_BREATH: {
		id: 11390,
		name: 'Aqua Breath',
		icon: 'https://xivapi.com/i/003000/003258.png',
		statusesApplied: [BLU_STATUSES.AQUA_BREATH],
		damageType: damageType.magic,
		damageAspect: damageAspect.water,
		elementType: elementType.umbral,
		attackPotency: 140,
		aoeAttackPotency: 70,
	},
	FLYING_FRENZY: {
		id: 11389,
		name: 'Flying Frenzy',
		icon: 'https://xivapi.com/i/003000/003257.png',
		damageType: damageType.blunt,
		elementType: elementType.physical,
		attackPotency: 150,
		aoeAttackPotency: 75,
	},
	DRILL_CANNONS: {
		id: 11398,
		name: 'Drill Cannons',
		icon: 'https://xivapi.com/i/003000/003266.png',
		damageType: damageType.piercing,
		elementType: elementType.physical,
		attackPotency: {
			'none': 200,
			'Petrification': 600,
		},
		aoeAttackPotency: {
			'none': 100,
			'Petrification': 300,
		},
	},
	HIGH_VOLTAGE: {
		id: 11387,
		name: 'High Voltage',
		icon: 'https://xivapi.com/i/003000/003255.png',
		damageType: damageType.magic,
		damageAspect: damageAspect.lightning,
		elementType: elementType.astral,
		attackPotency: {
			'none': 180,
			'Dropsy': 220,
		},
		aoeAttackPotency: {
			'none': 90,
			'Dropsy': 110,
		},
	},
	LOOM: {
		id: 11401,
		name: 'Loom',
		icon: 'https://xivapi.com/i/003000/003269.png',
	},
	FINAL_STING: {
		id: 11407,
		name: 'Final Sting',
		icon: 'https://xivapi.com/i/003000/003275.png',
		damageType: damageType.piercing,
		elementType: elementType.physical,
		attackPotency: 2000,
	},
	SONG_OF_TORMENT: {
		id: 11386,
		name: 'Song of Torment',
		icon: 'https://xivapi.com/i/003000/003254.png',
		statusesApplied: [BLU_STATUSES.BLEEDING],
		damageType: damageType.magic,
		damageAspect: damageAspect.unaspected,
		attackPotency: 50,
	},
	GLOWER: {
		id: 11404,
		name: 'Glower',
		icon: 'https://xivapi.com/i/003000/003272.png',
		damageType: damageType.magic,
		damageAspect: damageAspect.lightning,
		elementType: elementType.astral,
		attackPotency: 220,
		aoeAttackPotency: 110,
	},
	PLAINCRACKER: {
		id: 11391,
		name: 'Plaincracker',
		icon: 'https://xivapi.com/i/003000/003259.png',
		damageType: damageType.magic,
		damageAspect: damageAspect.earth,
		elementType: elementType.umbral,
		attackPotency: 220,
		aoeAttackPotency: 110,
	},
	BRISTLE: {
		id: 11393,
		name: 'Bristle',
		icon: 'https://xivapi.com/i/003000/003261.png',
		statusesApplied: [BLU_STATUSES.BRISTLE],
	},
	WHITE_WIND: {
		id: 11406,
		name: 'White Wind',
		icon: 'https://xivapi.com/i/003000/003274.png',
		notes: "Heal amount is equal to caster current HP."
	},
	LEVEL_5_PETRIFY: {
		id: 11414,
		name: 'Level 5 Petrify',
		icon: 'https://xivapi.com/i/003000/003282.png',
		statusesApplied: [BLU_STATUSES.PETRIFICATION],
	},
	SHARPENED_KNIFE: {
		id: 11400,
		name: 'Sharpened Knife',
		icon: 'https://xivapi.com/i/003000/003268.png',
		damageType: damageType.slashing,
		elementType: elementType.physical,
		attackPotency: {
			'none': 220,
			'Stun': 450,
		},
	},
	ICE_SPIKES: {
		id: 11418,
		name: 'Ice Spikes',
		icon: 'https://xivapi.com/i/003000/003286.png',
		statusesApplied: [BLU_STATUSES.ICE_SPIKES],
	},
	BLOOD_DRAIN: {
		id: 11395,
		name: 'Blood Drain',
		icon: 'https://xivapi.com/i/003000/003263.png',
		damageType: damageType.magic,
		damageAspect: damageAspect.unaspected,
		attackPotency: 50,
	},
	ACORN_BOMB: {
		id: 11392,
		name: 'Acorn Bomb',
		icon: 'https://xivapi.com/i/003000/003260.png',
	},
	BOMB_TOSS: {
		id: 11396,
		name: 'Bomb Toss',
		icon: 'https://xivapi.com/i/003000/003264.png',
		statusesApplied: [BLU_STATUSES.STUN],
		damageType: damageType.magic,
		damageAspect: damageAspect.fire,
		elementType: elementType.astral,
		attackPotency: 200,
		aoeAttackPotency: 100,
	},
	OFF_GUARD: {
		id: 11411,
		name: 'Off-guard',
		icon: 'https://xivapi.com/i/003000/003279.png',
		statusesApplied: [BLU_STATUSES.OFF_GUARD],
	},
	SELF_DESTRUCT: {
		id: 11408,
		name: 'Self-destruct',
		icon: 'https://xivapi.com/i/003000/003276.png',
		damageType: damageType.magic,
		damageAspect: damageAspect.fire,
		elementType: elementType.astral,
		aoeAttackPotency: {
			'none': 1500,
			'Toad Oil': 1800,
		},
	},
	TRANSFUSION: {
		id: 11409,
		name: 'Transfusion',
		icon: 'https://xivapi.com/i/003000/003277.png',
	},
	FAZE: {
		id: 11403,
		name: 'Faze',
		icon: 'https://xivapi.com/i/003000/003271.png',
		statusesApplied: [BLU_STATUSES.STUN],
	},
	FLYING_SARDINE: {
		id: 11423,
		name: 'Flying Sardine',
		icon: 'https://xivapi.com/i/003000/003291.png',
		damageType: damageType.piercing,
		elementType: elementType.physical,
		attackPotency: 10,
	},
	SNORT: {
		id: 11383,
		name: 'Snort',
		icon: 'https://xivapi.com/i/003000/003251.png',
	},
	FOUR_TONZE_WEIGHT: {
		id: 11384,
		name: '4-tonze Weight',
		icon: 'https://xivapi.com/i/003000/003252.png',
		damageType: damageType.blunt,
		elementType: elementType.physical,
		attackPotency: 200,
		aoeAttackPotency: 100,
	},
	THE_LOOK: {
		id: 11399,
		name: 'The Look',
		icon: 'https://xivapi.com/i/003000/003267.png',
		damageType: damageType.magic,
		damageAspect: damageAspect.unaspected,
		attackPotency: 220,
		aoeAttackPotency: 110,
	},
	BAD_BREATH: {
		id: 11388,
		name: 'Bad Breath',
		icon: 'https://xivapi.com/i/003000/003256.png',
		statusesApplied: [BLU_STATUSES.MALODOROUS, BLU_STATUSES.BAD_BREATH_POISON],
		damageType: damageType.magic,
		damageAspect: damageAspect.unaspected,
	},
	DIAMONDBACK: {
		id: 11424,
		name: 'Diamondback',
		icon: 'https://xivapi.com/i/003000/003292.png',
		statusesApplied: [BLU_STATUSES.DIAMONDBACK],
	},
	MIGHTY_GUARD: {
		id: 11417,
		name: 'Mighty Guard',
		icon: 'https://xivapi.com/i/003000/003285.png',
		statusesApplied: [BLU_STATUSES.MIGHTY_GUARD],
	},
	STICKY_TONGUE: {
		id: 11412,
		name: 'Sticky Tongue',
		icon: 'https://xivapi.com/i/003000/003280.png',
	},
	TOAD_OIL: {
		id: 11410,
		name: 'Toad Oil',
		icon: 'https://xivapi.com/i/003000/003278.png',
		statusesApplied: [BLU_STATUSES.TOAD_OIL],
	},
	THE_RAMS_VOICE: {
		id: 11419,
		name: 'The Ram\'s Voice',
		icon: 'https://xivapi.com/i/003000/003287.png',
		statusesApplied: [BLU_STATUSES.DEEP_FREEZE],
		damageType: damageType.magic,
		damageAspect: damageAspect.ice,
		elementType: elementType.umbral,
		attackPotency: 220,
		aoeAttackPotency: 110,
	},
	THE_DRAGONS_VOICE: {
		id: 11420,
		name: 'The Dragon\'s Voice',
		icon: 'https://xivapi.com/i/003000/003288.png',
		damageType: damageType.magic,
		damageAspect: damageAspect.lightning,
		elementType: elementType.astral,
		attackPotency: {
			'none': 200,
			'Deep Freeze': 400
		},
		aoeAttackPotency: {
			'none': 100,
			'Deep Freeze': 200,
		},
	},
	MISSILE: {
		id: 11405,
		name: 'Missile',
		icon: 'https://xivapi.com/i/003000/003273.png',
		damageType: damageType.magic,
		damageAspect: damageAspect.unaspected,
		notes: "Deals 50% of target current HP."
	},
	THOUSAND_NEEDLES: {
		id: 11397,
		name: '1000 Needles',
		icon: 'https://xivapi.com/i/003000/003265.png',
		damageType: damageType.piercing,
		elementType: elementType.physical,
		notes: "Deals exactly 1000 damage split equally between all targets hit."
	},
	INK_JET: {
		id: 11422,
		name: 'Ink Jet',
		icon: 'https://xivapi.com/i/003000/003290.png',
		damageType: damageType.magic,
		damageAspect: damageAspect.unaspected,
		attackPotency: 200,
		aoeAttackPotency: 100,
	},
	FIRE_ANGON: {
		id: 11425,
		name: 'Fire Angon',
		icon: 'https://xivapi.com/i/003000/003293.png',
		damageType: damageType.piercing,
		damageAspect: damageAspect.fire,
		elementType: elementType.physical,
		attackPotency: 200,
		aoeAttackPotency: 100,
		notes: "Damage type is both Fire and Piercing, but only gains a boost from Physical buffs."
	},
	MOON_FLUTE: {
		id: 11415,
		name: 'Moon Flute',
		icon: 'https://xivapi.com/i/003000/003283.png',
		statusesApplied: [BLU_STATUSES.WAXING_NOCTURNE, BLU_STATUSES.WANING_NOCTURNE],
	},
	TAIL_SCREW: {
		id: 11413,
		name: 'Tail Screw',
		icon: 'https://xivapi.com/i/003000/003281.png',
		notes: "Reduces target HP to 1."
	},
	MIND_BLAST: {
		id: 11394,
		name: 'Mind Blast',
		icon: 'https://xivapi.com/i/003000/003262.png',
		damageType: damageType.magic,
		damageAspect: damageAspect.unaspected,
		attackPotency: 200,
		aoeAttackPotency: 100,
	},
	DOOM: {
		id: 11416,
		name: 'Doom',
		icon: 'https://xivapi.com/i/003000/003284.png',
		statusesApplied: [BLU_STATUSES.DOOM],
	},
	PECULIAR_LIGHT: {
		id: 11421,
		name: 'Peculiar Light',
		icon: 'https://xivapi.com/i/003000/003289.png',
		statusesApplied: [BLU_STATUSES.PECULIAR_LIGHT],
	},
	FEATHER_RAIN: {
		id: 11426,
		name: 'Feather Rain',
		icon: 'https://xivapi.com/i/003000/003294.png',
		statusesApplied: [BLU_STATUSES.FEATHER_RAIN],
		damageType: damageType.magic,
		damageAspect: damageAspect.wind,
		elementType: elementType.astral,
		aoeAttackPotency: 220,
	},
	ERUPTION: {
		id: 11427,
		name: 'Eruption',
		icon: 'https://xivapi.com/i/003000/003295.png',
		damageType: damageType.magic,
		damageAspect: damageAspect.fire,
		elementType: elementType.astral,
		aoeAttackPotency: 300,
	},
	BLU_MOUNTAIN_BUSTER: {
		id: 11428,
		name: 'Mountain Buster',
		icon: 'https://xivapi.com/i/003000/003296.png',
		damageType: damageType.blunt,
		damageAspect: damageAspect.earth,
		elementType: elementType.umbral,
		attackPotency: 400,
		aoeAttackPotency: 200,
	},
	SHOCK_STRIKE: {
		id: 11429,
		name: 'Shock Strike',
		icon: 'https://xivapi.com/i/003000/003297.png',
		damageType: damageType.magic,
		damageAspect: damageAspect.lightning,
		elementType: elementType.astral,
		attackPotency: 400,
		aoeAttackPotency: 200,
	},
	GLASS_DANCE: {
		id: 11430,
		name: 'Glass Dance',
		icon: 'https://xivapi.com/i/003000/003298.png',
		damageType: damageType.magic,
		damageAspect: damageAspect.ice,
		elementType: elementType.umbral,
		attackPotency: 350,
		aoeAttackPotency: 175,
	},
	VEIL_OF_THE_WHORL: {
		id: 11431,
		name: 'Veil of the Whorl',
		icon: 'https://xivapi.com/i/003000/003299.png',
		statusesApplied: [BLU_STATUSES.VEIL_OF_THE_WHORL],
	},
	ALPINE_DRAFT: {
		id: 18295,
		name: 'Alpine Draft',
		icon: 'https://xivapi.com/i/003000/003300.png',
		damageType: damageType.magic,
		damageAspect: damageAspect.wind,
		elementType: elementType.astral,
		attackPotency: 220,
		aoeAttackPotency: 110,
	},
	PROTEAN_WAVE: {
		id: 18296,
		name: 'Protean Wave',
		icon: 'https://xivapi.com/i/003000/003301.png',
		damageType: damageType.magic,
		damageAspect: damageAspect.water,
		elementType: elementType.umbral,
		attackPotency: 220,
		aoeAttackPotency: 110,
	},
	NORTHERLIES: {
		id: 18297,
		name: 'Northerlies',
		icon: 'https://xivapi.com/i/003000/003302.png',
		damageType: damageType.magic,
		damageAspect: damageAspect.ice,
		elementType: elementType.umbral,
		attackPotency: 220,
		aoeAttackPotency: 110,
	},
	ELECTROGENESIS: {
		id: 18298,
		name: 'Electrogenesis',
		icon: 'https://xivapi.com/i/003000/003303.png',
		damageType: damageType.magic,
		damageAspect: damageAspect.lightning,
		elementType: elementType.astral,
		attackPotency: 220,
		aoeAttackPotency: 110,
	},
	KALTSTRAHL: {
		id: 18299,
		name: 'Kaltstrahl',
		icon: 'https://xivapi.com/i/003000/003304.png',
		damageType: damageType.slashing,
		elementType: elementType.physical,
		attackPotency: 220,
		aoeAttackPotency: 110,
	},
	ABYSSAL_TRANSFIXION: {
		id: 18300,
		name: 'Abyssal Transfixion',
		icon: 'https://xivapi.com/i/003000/003305.png',
		damageType: damageType.piercing,
		elementType: elementType.physical,
		attackPotency: 220,
	},
	CHIRP: {
		id: 18301,
		name: 'Chirp',
		icon: 'https://xivapi.com/i/003000/003306.png',
	},
	EERIE_SOUNDWAVE: {
		id: 18302,
		name: 'Eerie Soundwave',
		icon: 'https://xivapi.com/i/003000/003307.png',
	},
	POM_CURE: {
		id: 18303,
		name: 'Pom Cure',
		icon: 'https://xivapi.com/i/003000/003308.png',
		healPotency: {
			'none': 100,
			'Aetheric Mimicry: Healer': 500,
		},
	},
	GOBSKIN: {
		id: 18304,
		name: 'Gobskin',
		icon: 'https://xivapi.com/i/003000/003309.png',
		statusesApplied: [BLU_STATUSES.GOBSKIN],
	},
	magic_HAMMER: {
		id: 18305,
		name: 'Magic Hammer',
		icon: 'https://xivapi.com/i/003000/003310.png',
		statusesApplied: [BLU_STATUSES.MAGIC_HAMMER],
		damageType: damageType.magic,
		damageAspect: damageAspect.unaspected,
		attackPotency: 250,
		aoeAttackPotency: 125,
	},
	AVAIL: {
		id: 18306,
		name: 'Avail',
		icon: 'https://xivapi.com/i/003000/003311.png',
		statusesApplied: [BLU_STATUSES.AVAIL_MEATILY_SHIELDED, BLU_STATUSES.AVAIL_MEAT_SHIELD],
	},
	FROG_LEGS: {
		id: 18307,
		name: 'Frog Legs',
		icon: 'https://xivapi.com/i/003000/003312.png',
	},
	SONIC_BOOM: {
		id: 18308,
		name: 'Sonic Boom',
		icon: 'https://xivapi.com/i/003000/003313.png',
		damageType: damageType.magic,
		damageAspect: damageAspect.wind,
		elementType: elementType.astral,
		attackPotency: 210,
	},
	WHISTLE: {
		id: 18309,
		name: 'Whistle',
		icon: 'https://xivapi.com/i/003000/003314.png',
		statusesApplied: [BLU_STATUSES.WHISTLE],
	},
	WHITE_KNIGHTS_TOUR: {
		id: 18310,
		name: 'White Knight\'s Tour',
		icon: 'https://xivapi.com/i/003000/003315.png',
		statusesApplied: [BLU_STATUSES.SLOW],
		damageType: damageType.magic,
		damageAspect: damageAspect.unaspected,
		attackPotency: {
			'none': 200,
			'Bind': 400,
		},
		aoeAttackPotency: {
			'none': 100,
			'Bind': 200,
		},
	},
	BLACK_KNIGHTS_TOUR: {
		id: 18311,
		name: 'Black Knight\'s Tour',
		icon: 'https://xivapi.com/i/003000/003316.png',
		statusesApplied: [BLU_STATUSES.BIND],
		damageType: damageType.magic,
		damageAspect: damageAspect.unaspected,
		attackPotency: {
			'none': 200,
			'Slow': 400,
		},
		aoeAttackPotency: {
			'none': 100,
			'Slow': 200,
		},
	},
	LEVEL_5_DEATH: {
		id: 18312,
		name: 'Level 5 Death',
		icon: 'https://xivapi.com/i/003000/003317.png',
		damageType: damageType.magic,
		damageAspect: damageAspect.unaspected,
		notes: "Instantly kills targets with a level that is a multiple of 5."
	},
	LAUNCHER: {
		id: 18313,
		name: 'Launcher',
		icon: 'https://xivapi.com/i/003000/003318.png',
		damageType: damageType.magic,
		damageAspect: damageAspect.unaspected,
		notes: "Randomly deals damage equal to 50%, 30%, 20%, or 10% of target current HP."
	},
	PERPETUAL_RAY: {
		id: 18314,
		name: 'Perpetual Ray',
		icon: 'https://xivapi.com/i/003000/003319.png',
		statusesApplied: [BLU_STATUSES.STUN],
		damageType: damageType.magic,
		damageAspect: damageAspect.unaspected,
		attackPotency: 220,
	},
	CACTGUARD: {
		id: 18315,
		name: 'Cactguard',
		icon: 'https://xivapi.com/i/003000/003320.png',
		statusesApplied: [BLU_STATUSES.CACTGUARD],
	},
	REVENGE_BLAST: {
		id: 18316,
		name: 'Revenge Blast',
		icon: 'https://xivapi.com/i/003000/003321.png',
		damageType: damageType.blunt,
		elementType: elementType.physical,
		attackPotency: {
			'none': 50,
			'below 20% HP': 500,
		},
	},
	ANGEL_WHISPER: {
		id: 18317,
		name: 'Angel Whisper',
		icon: 'https://xivapi.com/i/003000/003322.png',
	},
	EXUVIATION: {
		id: 18318,
		name: 'Exuviation',
		icon: 'https://xivapi.com/i/003000/003323.png',
		aoeHealPotency: {
			'none': 50,
			'Aetheric Mimicry: Healer': 300,
		},
	},
	REFLUX: {
		id: 18319,
		name: 'Reflux',
		icon: 'https://xivapi.com/i/003000/003324.png',
		damageType: damageType.magic,
		damageAspect: damageAspect.lightning,
		elementType: elementType.astral,
		attackPotency: 220,
	},
	DEVOUR: {
		id: 18320,
		name: 'Devour',
		icon: 'https://xivapi.com/i/003000/003325.png',
		statusesApplied: [BLU_STATUSES.DEVOUR],
		damageType: damageType.magic,
		damageAspect: damageAspect.unaspected,
		attackPotency: 250,
		notes: "Restores an amount of own HP equal to damage dealt."
	},
	CONDENSED_LIBRA: {
		id: 18321,
		name: 'Condensed Libra',
		icon: 'https://xivapi.com/i/003000/003326.png',
		statusesApplied: [BLU_STATUSES.CONDENSED_LIBRA_ASTRAL, BLU_STATUSES.CONDENSED_LIBRA_UMBRAL, BLU_STATUSES.CONDENSED_LIBRA_PHYSICAL],
	},
	AETHERIAL_MIMICRY: {
		id: 18322,
		name: 'Aetherial Mimicry',
		icon: 'https://xivapi.com/i/003000/003327.png',
		statusesApplied: [BLU_STATUSES.MIMICRY_TANK, BLU_STATUSES.MIMICRY_DPS, BLU_STATUSES.MIMICRY_HEALER],
	},
	SURPANAKHA: {
		id: 18323,
		name: 'Surpanakha',
		icon: 'https://xivapi.com/i/003000/003328.png',
		charges: 4,
		statusesApplied: [BLU_STATUSES.SURPANAKHA],
		damageType: damageType.magic,
		damageAspect: damageAspect.earth,
		elementType: elementType.umbral,
		attackPotency: 200,
		aoeAttackPotency: 100,
		notes: "Boosts own damage based on stacks."
	},
	QUASAR: {
		id: 18324,
		name: 'Quasar',
		icon: 'https://xivapi.com/i/003000/003329.png',
		damageType: damageType.magic,
		damageAspect: damageAspect.unaspected,
		attackPotency: 300,
		aoeAttackPotency: 150,
	},
	J_KICK: {
		id: 18325,
		name: 'J Kick',
		icon: 'https://xivapi.com/i/003000/003330.png',
		damageType: damageType.blunt,
		elementType: elementType.physical,
		attackPotency: 300,
		aoeAttackPotency: 150,
	},
	TRIPLE_TRIDENT: {
		id: 23264,
		name: 'Triple Trident',
		icon: 'https://xivapi.com/i/003000/003331.png',
		damageType: damageType.piercing,
		elementType: elementType.physical,
		attackPotency: 150,
		notes: "Hits 3 times per cast. Buffs will apply to each hit individually."
	},
	TINGLE: {
		id: 23265,
		name: 'Tingle',
		icon: 'https://xivapi.com/i/003000/003332.png',
		statusesApplied: [BLU_STATUSES.TINGLING],
		damageType: damageType.magic,
		damageAspect: damageAspect.lightning,
		elementType: elementType.astral,
		attackPotency: 100,
		aoeAttackPotency: 50,
	},
	TATAMI_GAESHI: {
		id: 23266,
		name: 'Tatami-gaeshi',
		icon: 'https://xivapi.com/i/003000/003333.png',
		statusesApplied: [BLU_STATUSES.STUN],
		damageType: damageType.magic,
		damageAspect: damageAspect.unaspected,
		attackPotency: 220,
		aoeAttackPotency: 110,
	},
	COLD_FOG: {
		id: 23267,
		name: 'Cold Fog',
		icon: 'https://xivapi.com/i/003000/003334.png',
		statusesApplied: [BLU_STATUSES.COLD_FOG],
	},
	WHITE_DEATH: {
		id: 23268,
		name: 'White Death',
		icon: 'https://xivapi.com/i/003000/003335.png',
		statusesApplied: [BLU_STATUSES.DEEP_FREEZE],
		damageType: damageType.magic,
		damageAspect: damageAspect.ice,
		elementType: elementType.umbral,
		attackPotency: 400,
	},
	STOTRAM_ATTACK: {
		id: 23269,
		name: 'Stotram',
		icon: 'https://xivapi.com/i/003000/003336.png',
		damageType: damageType.magic,
		damageAspect: damageAspect.unaspected,
		aoeAttackPotency: 140,
		notes: "Shares a name with an AoE heal spell."
	},
	STOTRAM_HEAL: {
		id: 23416,
		name: 'Stotram',
		icon: 'https://xivapi.com/i/003000/003336.png',
		aoeHealPotency: 300,
		notes: "Shares a name with an AoE attack spell."
	},
	SAINTLY_BEAM: {
		id: 23270,
		name: 'Saintly Beam',
		icon: 'https://xivapi.com/i/003000/003337.png',
		damageType: damageType.magic,
		damageAspect: damageAspect.unaspected,
		aoeAttackPotency: {
			'none': 100,
			'Undead': 500,
		},
	},
	FECULENT_FLOOD: {
		id: 23271,
		name: 'Feculent Flood',
		icon: 'https://xivapi.com/i/003000/003338.png',
		damageType: damageType.magic,
		damageAspect: damageAspect.earth,
		elementType: elementType.umbral,
		attackPotency: 220,
		aoeAttackPotency: 110,
	},
	ANGELS_SNACK: {
		id: 23272,
		name: 'Angel\'s Snack',
		icon: 'https://xivapi.com/i/003000/003339.png',
		statusesApplied: [BLU_STATUSES.ANGELS_SNACK],
		aoeHealPotency: 400,
	},
	CHELONIAN_GATE: {
		id: 23273,
		name: 'Chelonian Gate',
		icon: 'https://xivapi.com//i/003000/003340.png',
		statusesApplied: [BLU_STATUSES.CHELONIAN_GATE, BLU_STATUSES.AUSPICIOUS_TRANCE],
	},
	DIVINE_CATARACT: {
		id: 23274,
		name: 'Divine Cataract',
		icon: 'https://xivapi.com//i/003000/003341.png',
		damageType: damageType.magic,
		damageAspect: damageAspect.water,
		elementType: elementType.umbral,
		AttackPotency: {
			'none': 500,
			'Aetheric Mimicry: Tank': 1000,
		},
		aoeAttackPotency: {
			'none': 250,
			'Aetheric Mimicry: Tank': 500,
		},
	},
	THE_ROSE_OF_DESTRUCTION: {
		id: 23275,
		name: 'The Rose of Destruction',
		icon: 'https://xivapi.com//i/003000/003342.png',
		damageType: damageType.magic,
		damageAspect: damageAspect.unaspected,
		attackPotency: 400,
	},
	BASIC_INSTINCT: {
		id: 23276,
		name: 'Basic Instinct',
		icon: 'https://xivapi.com//i/003000/003343.png',
		statusesApplied: [BLU_STATUSES.BASIC_INSTINCT]
	},
	ULTRAVIBRATION: {
		id: 23277,
		name: 'Ultravibration',
		icon: 'https://xivapi.com//i/003000/003344.png',
		notes: "Instantly kills any target inflicted with Deep Freeze."
	},
	BLAZE: {
		id: 23278,
		name: 'Blaze',
		icon: 'https://xivapi.com//i/003000/003345.png',
		damageType: damageType.magic,
		damageAspect: damageAspect.ice,	// not a typo, this is ice, not fire
		elementType: elementType.umbral,
		attackPotency: 220,
		aoeAttackPotency: 110,
	},
	MUSTARD_BOMB: {
		id: 23279,
		name: 'Mustard Bomb',
		icon: 'https://xivapi.com//i/003000/003346.png',
		statusesApplied: [BLU_STATUSES.INCENDIARY_BURNS],
		damageType: damageType.magic,
		damageAspect: damageAspect.fire,
		elementType: elementType.astral,
		attackPotency: 220,
		aoeAttackPotency: 110,
	},
	DRAGON_FORCE: {
		id: 23280,
		name: 'Dragon Force',
		icon: 'https://xivapi.com//i/003000/003347.png',
		statusesApplied: [BLU_STATUSES.DRAGON_FORCE],
	},
	AETHERIAL_SPARK: {
		id: 23281,
		name: 'Aetherial Spark',
		icon: 'https://xivapi.com//i/003000/003348.png',
		statusesApplied: [BLU_STATUSES.BLEEDING],
		damageType: damageType.magic,
		damageAspect: damageAspect.unaspected,
		aoeAttackPotency: 50,
	},
	HYDRO_PULL: {
		id: 23282,
		name: 'Hydro Pull',
		icon: 'https://xivapi.com//i/003000/003349.png',
		damageType: damageType.magic,
		damageAspect: damageAspect.water,
		elementType: elementType.umbral,
		attackPotency: 220,
		aoeAttackPotency: 110,
	},
	MALEDICTION_OF_WATER: {
		id: 23283,
		name: 'Malediction of Water',
		icon: 'https://xivapi.com//i/003000/003350.png',
		damageType: damageType.magic,
		damageAspect: damageAspect.water,
		elementType: elementType.umbral,
		attackPotency: 200,
		aoeAttackPotency: 100,
	},
	CHOCO_METEOR: {
		id: 23284,
		name: 'Choco Meteor',
		icon: 'https://xivapi.com//i/003000/003351.png',
		damageType: damageType.magic,
		damageAspect: damageAspect.unaspected,
		attackPotency: {
			'none': 200,
			'in party with personal chocobo': 300,
		},
		aoeAttackPotency: {
			'none': 100,
			'in party with personal chocobo': 150,
		},
	},
	MATRA_MAGIC: {
		id: 23285,
		name: 'Matra Magic',
		icon: 'https://xivapi.com//i/003000/003352.png',
		damageType: damageType.magic,
		damageAspect: damageAspect.unaspected,
		attackPotency: {
			'none': 50,
			'Aetheric Mimicry: DPS': 100,
		},
		notes: "Hits 8 times per cast. Buffs will apply to each hit individually."
	},
	PERIPHERAL_SYNTHESIS: {
		id: 23286,
		name: 'Peripheral Synthesis',
		icon: 'https://xivapi.com//i/003000/003353.png',
		statusesApplied: [BLU_STATUSES.LIGHTHEADED],
		damageType: damageType.blunt,
		elementType: elementType.physical,
		attackPotency: {
			'none': 220,
			'Lightheaded': 400,
		},
		aoeAttackPotency: {
			'none': 110,
			'Lightheaded': 200,
		},
	},
	BOTH_ENDS: {
		id: 23287,
		name: 'Both Ends',
		icon: 'https://xivapi.com//i/003000/003354.png',
		damageType: damageType.magic,
		damageAspect: damageAspect.unaspected,
		aoeAttackPotency: 600,
	},
	PHANTOM_FLURRY: {
		id: 23288,
		name: 'Phantom Flurry',
		icon: 'https://xivapi.com//i/003000/003355.png',
		statusesApplied: [BLU_STATUSES.PHANTOM_FLURRY],
		damageType: damageType.magic,
		damageAspect: damageAspect.unaspected,
	},
	PHANTOM_FLURRY_KICK: { // This is what Phantom Flurry turns into while the effect is channeling
		id: 23289,
		name: 'Phantom Flurry',
		icon: 'https://xivapi.com//i/003000/003356.png',
		damageType: damageType.magic,
		damageAspect: damageAspect.unaspected,
		attackPotency: 600,
		aoeAttackPotency: 300,
	},
	NIGHTBLOOM: {
		id: 23290,
		name: 'Nightbloom',
		icon: 'https://xivapi.com//i/003000/003357.png',
		statusesApplied: [BLU_STATUSES.BLEEDING],
		damageType: damageType.magic,
		damageAspect: damageAspect.unaspected,
		attackPotency: 400,
		aoeAttackPotency: 200,
	},
	GOBLIN_PUNCH: {
		id: 34563,
		name: 'Goblin Punch',
		icon: 'https://xivapi.com/i/003000/003358.png',
		damageType: damageType.blunt,
		elementType: elementType.physical,
		attackPotency: {
			'none': 120,
			'front positional': 220,
			'Mighty Guard': 220,
			'Mighty Guard + front positional': 320,
		},
	},
	RIGHT_ROUND: {
		id: 34564,
		name: 'Right Round',
		icon: 'https://xivapi.com/i/003000/003359.png',
		damageType: damageType.blunt,
		elementType: elementType.physical,
		aoeAttackPotency: 110,
	},
	SCHILTRON: {
		id: 34565,
		name: 'Schiltron',
		icon: 'https://xivapi.com/i/003000/003360.png',
		statusesApplied: [BLU_STATUSES.SCHILTRON],
	},
	REHYDRATION: {
		id: 34566,
		name: 'Rehydration',
		icon: 'https://xivapi.com/i/003000/003361.png',
		healPotency: 600,
	},
	BREATH_OF_MAGIC: {
		id: 34567,
		name: 'Breath of Magic',
		icon: 'https://xivapi.com/i/003000/003362.png',
		damageType: damageType.magic,
		damageAspect: damageAspect.unaspected,
		statusesApplied: [BLU_STATUSES.BREATH_OF_MAGIC],
	},
	WILD_RAGE: {
		id: 34568,
		name: 'Wild Rage',
		icon: 'https://xivapi.com/i/003000/003363.png',
		damageType: damageType.blunt,
		elementType: elementType.physical,
		attackPotency: 500,
		aoeAttackPotency: 250,
		notes: "Costs 50% of maximum HP to cast."
	},
	PEAT_PELT: {
		id: 34569,
		name: 'Peat Pelt',
		icon: 'https://xivapi.com/i/003000/003364.png',
		statusesApplied: [BLU_STATUSES.BEGRIMED],
		damageType: damageType.magic,
		damageAspect: damageAspect.earth,
		elementType: elementType.umbral,
		attackPotency: 100,
		aoeAttackPotency: 50,
	},
	DEEP_CLEAN: {
		id: 34570,
		name: 'Deep Clean',
		icon: 'https://xivapi.com/i/003000/003365.png',
		statusesApplied: [BLU_STATUSES.SPICK_AND_SPAN],
		damageType: damageType.blunt,
		elementType: elementType.physical,
		attackPotency: 220,
		aoeAttackPotency: 110,
	},
	RUBY_DYNAMICS: {
		id: 34571,
		name: 'Ruby Dynamics',
		icon: 'https://xivapi.com/i/003000/003366.png',
		damageType: damageType.slashing,
		elementType: elementType.physical,
		aoeAttackPotency: 220,
	},
	DIVINATION_RUNE: {
		id: 34572,
		name: 'Divination Rune',
		icon: 'https://xivapi.com/i/003000/003367.png',
		damageType: damageType.magic,
		damageAspect: damageAspect.unaspected,
		aoeAttackPotency: 100,
	},
	DIMENSIONAL_SHIFT: {
		id: 34573,
		name: 'Dimensional Shift',
		icon: 'https://xivapi.com/i/003000/003368.png',
		damageType: damageType.magic,
		damageAspect: damageAspect.unaspected,
		notes: "Deals 30% of target current HP."
	},
	CONVICTION_MARCATO: {
		id: 34574,
		name: 'Conviction Marcato',
		icon: 'https://xivapi.com/i/003000/003369.png',
		damageType: damageType.magic,
		damageAspect: damageAspect.unaspected,
		attackPotency: {
			'none': 220,
			'Winged Redemption': 440,
		},
		aoeAttackPotency: {
			'none': 110,
			'Winged Redemption': 220,
		},
	},
	FORCE_FIELD: {
		id: 34575,
		name: 'Force Field',
		icon: 'https://xivapi.com/i/003000/003370.png',
		statusesApplied: [BLU_STATUSES.BLU_PHYSICAL_VULN_DOWN, BLU_STATUSES.BLU_MAGIC_VULN_DOWN],
	},
	WINGED_REPROBATION: {
		id: 34576,
		name: 'Winged Reprobation',
		icon: 'https://xivapi.com/i/003000/003371.png',
		statusesApplied: [BLU_STATUSES.WINGED_REPROBATION, BLU_STATUSES.WINGED_REDEMPTION],
		damageType: damageType.piercing,
		elementType: elementType.physical,
		attackPotency: {
			'none': 300,
			'Winged Reprobation x3': 400,
		},
		aoeAttackPotency: {
			'none': 150,
			'Winged Reprobation x3': 200,
		},
	},
	LASER_EYE: {
		id: 34577,
		name: 'Laser Eye',
		icon: 'https://xivapi.com/i/003000/003372.png',
		damageType: damageType.magic,
		damageAspect: damageAspect.unaspected,
		attackPotency: 220,
		aoeAttackPotency: 110,
	},
	CANDY_CANE: {
		id: 34578,
		name: 'Candy Cane',
		icon: 'https://xivapi.com/i/003000/003373.png',
		statusesApplied: [BLU_STATUSES.CANDY_CANE],
		damageType: damageType.magic,
		damageAspect: damageAspect.unaspected,
		attackPotency: 250,
		aoeAttackPotency: 125,
	},
	MORTAL_FLAME: {
		id: 34579,
		name: 'Mortal Flame',
		icon: 'https://xivapi.com/i/003000/003374.png',
		statusesApplied: [BLU_STATUSES.MORTAL_FLAME],
		damageType: damageType.magic,
		damageAspect: damageAspect.fire,
		elementType: elementType.astral,
	},
	SEA_SHANTY: {
		id: 34580,
		name: 'Sea Shanty',
		icon: 'https://xivapi.com/i/003000/003375.png',
		damageType: damageType.magic,
		damageAspect: damageAspect.water,
		elementType: elementType.umbral,
		aoeAttackPotency: {
			'none': 500,
			'weather = rain, showers, or thunderstorms': 1000,
		},
	},
	APOKALYPSIS: {
		id: 34581,
		name: 'Apokalypsis',
		icon: 'https://xivapi.com/i/003000/003376.png',
		statusesApplied: [BLU_STATUSES.APOKALYPSIS],
		damageType: damageType.magic,
		damageAspect: damageAspect.unaspected,	
	},
	BEING_MORTAL: {
		id: 34582,
		name: 'Being Mortal',
		icon: 'https://xivapi.com/i/003000/003377.png',
		damageType: damageType.magic,
		damageAspect: damageAspect.unaspected,
		attackPotency: 800,
		aoeAttackPotency: 400,
	},
}
